const PARAMS = {
  DUREE_INCUBATION: 1000,
  DUREE_PRE_CONTAGION: 600,
  POURCENT_CONTAGION: 100,
  DUREE_DECES: 10000,
  POURCENT_MORTALITE: 20,
  DISTANCE_MIN_CONTAGION: 20,
}

Object.freeze(PARAMS)
